# Generated by Django 5.1 on 2023-11-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauthapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
